# Generated by Django 5.0.7 on 2024-08-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmsg',
            name='topic',
            field=models.CharField(default='topic/default', max_length=30),
        ),
    ]
