# Generated by Django 5.0.7 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttclient', '0002_topicmsg_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttserver',
            name='topic',
            field=models.CharField(default='topic/default', max_length=30),
        ),
    ]
