# Generated by Django 5.0.7 on 2024-08-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttclient', '0003_mqttserver_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttserver',
            name='topic',
        ),
        migrations.CreateModel(
            name='MqttTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='mqttclient.mqttserver')),
            ],
        ),
        migrations.CreateModel(
            name='MqttMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('rastime', models.DateTimeField(auto_now_add=True)),
                ('msgtype', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mqttclient.mqtttopic')),
            ],
        ),
        migrations.DeleteModel(
            name='TopicMsg',
        ),
    ]
