# Generated by Django 5.0.7 on 2024-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('nummoney', models.FloatField()),
                ('paytime', models.DateTimeField(auto_now_add=True)),
                ('paytype', models.IntegerField(choices=[(1, '运动'), (2, '吃饭'), (3, '游戏'), (4, '学习'), (5, '借钱')], default=4)),
            ],
        ),
    ]
